#!/usr/bin/env python3
"""
scripts/build_test_suite.py
Generates the comprehensive test suite in test_cases.jsonl:
- Preserves existing TC-001 through TC-097
- Adds TC-098 and TC-099 (Draggable HUDs & Anti-Overlap Repulsion)
- Adds dual-scenario regression tests for all 76 UI controls (TC-C01-A/B to TC-C76-A/B)
- Tags tests with rotating models from modelsfortests
"""

import json
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parent.parent
TEST_CASES_FILE = ROOT_DIR / "test_cases.jsonl"

UI_CONTROLS = [
    ("C01", "Project Selector Dropdown", "SpatialTopPill", "Project Lifecycle", "Building-Architecture.ifc",
     "Open dropdown and select a different active project",
     "Switch back to initial project; verify canvas updates"),
    ("C02", "Hierarchy Tree Toggle", "SpatialTopPill", "Spatial Hierarchy", "Ifc2x3_Duplex_Architecture.ifc",
     "Click tree icon: verify left drawer opens and expands",
     "Click tree icon again: verify left drawer collapses cleanly"),
    ("C03", "Category Filter: Walls", "SpatialTopPill", "Visibility & Styles", "Ifc2x3_Duplex_Architecture.ifc",
     "Uncheck 'Walls': verify all wall meshes become hidden",
     "Re-check 'Walls': verify walls re-render with PBR materials"),
    ("C04", "Category Filter: Slabs", "SpatialTopPill", "Visibility & Styles", "Ifc2x3_Duplex_Architecture.ifc",
     "Uncheck 'Slabs': verify slab meshes are invisible",
     "Re-check 'Slabs': verify slabs return to visible state"),
    ("C05", "Category Filter: Columns", "SpatialTopPill", "Visibility & Styles", "Ifc4_Revit_STR.ifc",
     "Uncheck 'Columns': verify columns are hidden",
     "Re-check 'Columns': verify columns return"),
    ("C06", "Category Filter: Doors", "SpatialTopPill", "Visibility & Styles", "Ifc4_SampleHouse.ifc",
     "Uncheck 'Doors': verify door geometries disappear",
     "Re-check 'Doors': verify doors re-appear"),
    ("C07", "Category Filter: Windows", "SpatialTopPill", "Visibility & Styles", "Ifc4_SampleHouse.ifc",
     "Uncheck 'Windows': verify window meshes are hidden",
     "Re-check 'Windows': verify window transparent materials return"),
    ("C08", "Federation Toggle Button", "SpatialTopPill", "Federation & Clashes", "Ifc2x3_Duplex_MEP.ifc",
     "Click federation icon: verify federation modal mounts",
     "Click outside / toggle: verify modal unmounts"),
    ("C09", "Clash Inspector Toggle", "SpatialTopPill", "Federation & Clashes", "Ifc2x3_Duplex_MEP.ifc",
     "Click clash icon: verify floating clash HUD mounts",
     "Close clash HUD: verify unmount and markers cleanup"),
    ("C10", "CAD Modeling Toggle", "SpatialTopPill", "Parametric CAD", "Ifc4_SampleHouse.ifc",
     "Click CAD icon: verify floating CAD toolbar mounts",
     "Toggle CAD icon off: verify CAD toolbar and previews clear"),
    ("C11", "BCF Manager Toggle", "SpatialTopPill", "Collaboration & Issues", "Ifc2x3_Duplex_MEP.ifc",
     "Click BCF icon: verify BCF 2.1 modal opens with topics list",
     "Close BCF modal: verify return to 3D canvas"),
    ("C12", "Timeline Scrubber Toggle", "SpatialTopPill", "Session Audit & Playback", "Ifc4_Revit_STR.ifc",
     "Click timeline icon: verify floating scrubber HUD mounts",
     "Toggle timeline off: verify scrubber HUD unmounts"),
    ("C13", "Omnibar Trigger Button", "SpatialTopPill", "Navigation & Search", "Building-Architecture.ifc",
     "Click search / Ctrl+K button: verify Omnibar opens",
     "Press ESC: verify Omnibar closes and focus returns"),
    ("C14", "Property Inspector Toggle", "SpatialTopPill", "Property Inspection", "Ifc2x3_Duplex_Architecture.ifc",
     "Click properties icon with selected element: verify drawer opens",
     "Click close drawer: verify drawer slides shut"),
    ("C15", "AI Copilot Toggle", "SpatialTopPill", "AI BIM Copilot", "Ifc2x3_Duplex_Architecture.ifc",
     "Click copilot icon: verify copilot drawer mounts",
     "Toggle copilot off: verify canvas width reclaims space"),
    ("C16", "New Project Modal Button", "SpatialTopPill", "Project Lifecycle", "Building-Architecture.ifc",
     "Click '+' button: verify new project template modal opens",
     "Click Cancel in modal: verify modal cleanly dismisses"),
    ("C17", "Upload IFC File Button", "SpatialTopPill", "Project Lifecycle", "Building-Architecture.ifc",
     "Click upload button: verify upload dropzone modal mounts",
     "Dismiss upload modal via close button"),
    ("C18", "Export IFC File Button", "SpatialTopPill", "Project Lifecycle", "Ifc2x3_Duplex_Architecture.ifc",
     "Click export button: verify 200 response and valid IFC download",
     "Modify element placement then export: verify STEP placement updated"),
    ("C19", "Select Mode Button", "SpatialBottomDock", "3D Viewport Controls", "Ifc2x3_Duplex_Architecture.ifc",
     "Click Select mode: verify cursor resets and gizmo detaches",
     "Press 'Space' hotkey: verify select mode activates"),
    ("C20", "Translate (G) Button", "SpatialBottomDock", "3D Viewport Controls", "Ifc2x3_Duplex_Architecture.ifc",
     "Click Translate mode: verify translation transform gizmo attaches",
     "Press 'G' hotkey: verify gizmo mode switches to translate"),
    ("C21", "Rotate (R) Button", "SpatialBottomDock", "3D Viewport Controls", "Ifc2x3_Duplex_Architecture.ifc",
     "Click Rotate mode: verify rotation transform gizmo rings attach",
     "Press 'R' hotkey: verify gizmo mode switches to rotate"),
    ("C22", "Grid Snap Toggle Button", "SpatialBottomDock", "3D Viewport Controls", "Ifc2x3_Duplex_Architecture.ifc",
     "Toggle grid snap off: verify continuous float transform",
     "Toggle grid snap on: verify increments snap to grid"),
    ("C23", "Section Plane Toggle", "SpatialBottomDock", "BIM Tools & Sectioning", "Ifc4_SampleHouse.ifc",
     "Click section toggle: verify orthogonal clipping plane activates",
     "Toggle off: verify full model unclipped geometry restores"),
    ("C24", "Section Axis: X / Y / Z", "SpatialBottomDock", "BIM Tools & Sectioning", "Ifc4_SampleHouse.ifc",
     "Switch section axis to 'Z': verify horizontal plan cut",
     "Switch section axis to 'X': verify vertical transverse cut"),
    ("C25", "Section Invert Button", "SpatialBottomDock", "BIM Tools & Sectioning", "Ifc4_SampleHouse.ifc",
     "Click invert: verify clipped side reverses",
     "Click invert again: verify original clip orientation restores"),
    ("C26", "Measure Tool Button", "SpatialBottomDock", "3D Measurement", "Ifc2x3_SampleCastle.ifc",
     "Click measure: verify measure mode active, crosshair cursor, banner",
     "Click measure again: verify measure mode exits, banner leaves"),
    ("C27", "Clear Measurements Button", "SpatialBottomDock", "3D Measurement", "Ifc2x3_Duplex_Architecture.ifc",
     "Click Clear: verify active dimension lines and screen tags removed",
     "Verify button hides when count is 0"),
    ("C28", "Render Style: PBR / Shaded", "SpatialBottomDock", "Visibility & Styles", "Ifc2x3_Duplex_Architecture.ifc",
     "Select Shaded: verify category color representation",
     "Switch between Shaded and Ghost: verify material opacity update"),
    ("C29", "Render Style: Wireframe", "SpatialBottomDock", "Visibility & Styles", "Ifc4_SampleHouse.ifc",
     "Select Wireframe: verify meshes render in wireframe lines",
     "Switch from Wireframe back to Shaded: verify solid surfaces restore"),
    ("C30", "Render Style: Discipline Mode", "SpatialBottomDock", "Visibility & Styles", "Ifc2x3_Duplex_MEP.ifc",
     "Select Discipline: verify ARCH, STRUCT, MEP color coding",
     "Revert to Shaded: verify default material palettes"),
    ("C31", "Render Style: Diff Mode", "SpatialBottomDock", "Session Audit & Playback", "Ifc4_Revit_STR.ifc",
     "Select Diff: verify emerald/amber audit shader highlights",
     "Select Diff with no modifications: verify neutral ghost style"),
    ("C32", "View Preset: ISO", "ViewControlsHud", "View Controls & Orientation", "Ifc2x3_SampleCastle.ifc",
     "Click ISO: verify camera moves to diagonal perspective viewpoint",
     "Orbit away, then click ISO: verify camera snaps back to isometric"),
    ("C33", "View Preset: TOP", "ViewControlsHud", "View Controls & Orientation", "Ifc2x3_SampleCastle.ifc",
     "Click TOP: verify top plan view orientation (x=0, z=0, y>0)",
     "Verify top view maintains bounding center target"),
    ("C34", "View Preset: FRONT", "ViewControlsHud", "View Controls & Orientation", "Ifc2x3_SampleCastle.ifc",
     "Click FRONT: verify front elevation orientation (y=0, z>0)",
     "Verify front view displays building elevation upright"),
    ("C35", "View Preset: SIDE", "ViewControlsHud", "View Controls & Orientation", "Ifc2x3_SampleCastle.ifc",
     "Click SIDE: verify side elevation orientation (x>0, y=0, z=0)",
     "Verify lateral profile view alignment"),
    ("C36", "Coordinate HUD Display", "CoordinateHud", "Product Presence", "Ifc2x3_Duplex_Architecture.ifc",
     "Move cursor over canvas: verify X/Y/Z coordinate readouts update",
     "Select an element: verify selection coordinates match bounding center"),
    ("C37", "3D Canvas Orbit Drag", "ThreeViewport", "3D Viewport Controls", "Ifc2x3_SampleCastle.ifc",
     "Left-drag mouse: verify camera yaw/pitch changes smoothly",
     "Measure mode orbit isolation: verify left-click places points without camera spin"),
    ("C38", "3D Canvas Pan Drag", "ThreeViewport", "3D Viewport Controls", "Ifc2x3_SampleCastle.ifc",
     "Right-drag mouse: verify camera pan translates target",
     "Pan across screen: verify scene stays responsive without jitter"),
    ("C39", "3D Canvas Zoom Wheel", "ThreeViewport", "3D Viewport Controls", "Ifc2x3_Duplex_Architecture.ifc",
     "Scroll mouse wheel up: verify camera distance zooms in",
     "Scroll mouse wheel down: verify camera distance zooms out within clamp bounds"),
    ("C40", "Direct Raycast Selection", "ThreeViewport", "3D Viewport Controls", "Ifc2x3_SampleCastle.ifc",
     "Click directly on wall mesh: verify element selected and outlined",
     "Click on background empty space: verify selection clears"),
    ("C41", "Measurement Point 1 Snapping", "ThreeViewport", "3D Measurement", "Ifc2x3_SampleCastle.ifc",
     "Hover vertex in measure mode: verify cyan snap indicator on true vertex",
     "Hover edge midpoint: verify amber snap indicator on edge"),
    ("C42", "Measurement Point 2 & Dimension Line", "ThreeViewport", "3D Measurement", "Ifc2x3_SampleCastle.ifc",
     "Click point 1 then click point 2: verify 3D line placed with floating badge",
     "Hover around point 2 before clicking: verify live Euclidean distance readout in HUD"),
    ("C43", "Measurement ESC & Cancel", "ThreeViewport", "3D Measurement", "Ifc2x3_Duplex_Architecture.ifc",
     "Pin point 1, press ESC: verify pending rubber-band canceled, prompt resets",
     "Press ESC in idle measure mode: verify measure tool completely exits"),
    ("C44", "Gizmo Axis Translate Drag", "ThreeViewport", "3D Viewport Controls", "Ifc2x3_Duplex_Architecture.ifc",
     "Drag X-axis red gizmo handle: verify mesh translates along X",
     "Release drag: verify backend placement sync returns 200"),
    ("C45", "Gizmo Axis Rotate Drag", "ThreeViewport", "3D Viewport Controls", "Ifc2x3_Duplex_Architecture.ifc",
     "Drag Y-axis green ring: verify mesh rotates around vertical axis",
     "Release drag: verify rotation matrix persisted in database"),
    ("C46", "Hierarchy Drawer Close", "SpatialTree", "Spatial Hierarchy", "Ifc2x3_Duplex_Architecture.ifc",
     "Click collapse button: verify tree drawer animates closed",
     "Check canvas: verify coordinate HUD adjusts margin seamlessly"),
    ("C47", "Tree Node Expand/Collapse", "SpatialTree", "Spatial Hierarchy", "Ifc2x3_Duplex_Architecture.ifc",
     "Click chevron on IfcBuildingStorey: verify child elements expand",
     "Click chevron again: verify children collapse"),
    ("C48", "Tree Node Selection", "SpatialTree", "Spatial Hierarchy", "Ifc2x3_Duplex_Architecture.ifc",
     "Click tree node for a slab: verify slab highlighted in 3D viewport",
     "Click different node: verify selection updates seamlessly"),
    ("C49", "Tree Node Isolate Toggle", "SpatialTree", "Spatial Hierarchy", "Ifc2x3_Duplex_Architecture.ifc",
     "Click eye icon on element: verify all other elements ghosted/hidden",
     "Click eye icon again: verify entire model un-isolated"),
    ("C50", "Property Drawer Close", "PropertyInspector", "Property Inspection", "Ifc2x3_Duplex_Architecture.ifc",
     "Click 'X' close button: verify property inspector drawer closes",
     "Select element again: verify drawer re-opens with clean state"),
    ("C51", "Property Set Accordion", "PropertyInspector", "Property Inspection", "Ifc2x3_Duplex_Architecture.ifc",
     "Click 'Pset_WallCommon' header: verify accordion collapses",
     "Click header again: verify accordion expands and attributes visible"),
    ("C52", "Inline Property Edit", "PropertyInspector", "Property Inspection", "Ifc2x3_Duplex_Architecture.ifc",
     "Edit property string value & blur: verify PATCH API returns 200",
     "Refresh property data: verify edited value persists in database"),
    ("C53", "Omnibar Search Input", "SpatialOmnibar", "Navigation & Search", "Building-Architecture.ifc",
     "Type 'Wall' in search input: verify instant filtered results list",
     "Type express ID '#120': verify direct element match"),
    ("C54", "Omnibar Result Select", "SpatialOmnibar", "Navigation & Search", "Ifc2x3_Duplex_Architecture.ifc",
     "Click search result item: verify Omnibar closes and element focused",
     "Press Enter on highlighted result: verify element selection"),
    ("C55", "Copilot Drawer Close", "CopilotSidebar", "AI BIM Copilot", "Ifc2x3_Duplex_Architecture.ifc",
     "Click 'X' in copilot header: verify copilot drawer closes",
     "Verify canvas reclaims full width"),
    ("C56", "Copilot Chat Submit", "CopilotSidebar", "AI BIM Copilot", "Ifc2x3_Duplex_Architecture.ifc",
     "Type prompt 'How many walls in model?': verify assistant reply",
     "Submit query: verify model query tool call executes"),
    ("C57", "CAD Wall Tool Button", "CadToolbar", "Parametric CAD", "Ifc4_SampleHouse.ifc",
     "Click Wall tool: verify wall preview helper attaches to cursor",
     "Click start and end points: verify IfcWall synthesized and rendered"),
    ("C58", "CAD Slab Tool Button", "CadToolbar", "Parametric CAD", "Ifc4_SampleHouse.ifc",
     "Click Slab tool: verify rectangular boundary preview helper",
     "Click corner points: verify IfcSlab extruded and placed"),
    ("C59", "CAD Column Tool Button", "CadToolbar", "Parametric CAD", "Ifc4_SampleHouse.ifc",
     "Click Column tool: verify vertical column prism preview",
     "Click ground plane: verify IfcColumn synthesized at elevation"),
    ("C60", "CAD Door Opening Button", "CadToolbar", "Parametric CAD", "Ifc4_SampleHouse.ifc",
     "Click Door tool and select host wall: verify opening void cut",
     "Verify door panel inserted into host wall void"),
    ("C61", "CAD Window Opening Button", "CadToolbar", "Parametric CAD", "Ifc4_SampleHouse.ifc",
     "Click Window tool: verify sill elevation offset opening void",
     "Verify window frame inserted into host wall void"),
    ("C62", "CAD Undo Button", "CadToolbar", "Parametric CAD", "Ifc4_SampleHouse.ifc",
     "Click Undo button: verify last created CAD entity removed from scene",
     "Verify transaction status updates to UNDONE"),
    ("C63", "CAD Redo Button", "CadToolbar", "Parametric CAD", "Ifc4_SampleHouse.ifc",
     "Click Redo button: verify undone CAD entity re-synthesized",
     "Verify transaction status restores to ACTIVE"),
    ("C64", "CAD History Flyout Button", "CadToolbar", "Parametric CAD", "Ifc4_SampleHouse.ifc",
     "Click History button: verify stack list of CAD operations mounts",
     "Inspect history entries: verify action types and IDs match"),
    ("C65", "BCF Create Topic Submit", "BcfManagerModal", "Collaboration & Issues", "Ifc2x3_Duplex_MEP.ifc",
     "Fill title, description, priority and click Create: verify topic added",
     "Verify created topic contains current 3D camera viewpoint"),
    ("C66", "BCF Import Clashes Button", "BcfManagerModal", "Collaboration & Issues", "Ifc2x3_Duplex_MEP.ifc",
     "Run clash check then click Import Clashes: verify clash topics created",
     "Inspect clash topic: verify attached camera focus on collision"),
    ("C67", "BCF Export .bcfzip Button", "BcfManagerModal", "Collaboration & Issues", "Ifc2x3_Duplex_MEP.ifc",
     "Click Export: verify download of standard .bcfzip archive",
     "Verify archive contains markup.bcf and viewpoint.bcfv"),
    ("C68", "Timeline Play/Pause", "TimelineScrubber", "Session Audit & Playback", "Ifc4_Revit_STR.ifc",
     "Click Play button: verify scrubber auto-advances through events",
     "Click Pause button: verify scrubber halts on active event"),
    ("C69", "Timeline Step Buttons", "TimelineScrubber", "Session Audit & Playback", "Ifc4_Revit_STR.ifc",
     "Click Step Next: verify index advances and affected element selected",
     "Click Step Prev: verify index decrements and prior element focused"),
    ("C70", "Clash Run Check Button", "ClashInspector", "Federation & Clashes", "Ifc2x3_Duplex_MEP.ifc",
     "Set tolerance 0.05m and click Run: verify collision list populated",
     "Change tolerance to 0.01m: verify clash count updates"),
    ("C71", "Clash Item Focus Click", "ClashInspector", "Federation & Clashes", "Ifc2x3_Duplex_MEP.ifc",
     "Click clash card: verify camera animates to clash center",
     "Verify 3D clash marker and collision wireframe render"),
    ("C72", "Draggable Top Bar Handle", "SpatialTopPill", "Draggable Canvas Bars", "Building-Architecture.ifc",
     "Drag Top Pill grip by dx: 40, dy: 30: verify bar moves to new coordinates",
     "Attempt dragging Top Pill past window edge: verify boundary clamping"),
    ("C73", "Draggable Bottom Dock", "SpatialBottomDock", "Draggable Canvas Bars", "Building-Architecture.ifc",
     "Drag Bottom Dock grip by dx: -50, dy: -40: verify position updates",
     "Release drag: verify dock maintains position without reset"),
    ("C74", "Draggable View Controls", "ViewControlsHud", "Draggable Canvas Bars", "Ifc2x3_SampleCastle.ifc",
     "Drag View Controls grip by dx: -80, dy: 60: verify bar moves",
     "Verify view buttons remain fully interactive in new position"),
    ("C75", "Draggable CAD Toolbar", "CadToolbar", "Draggable Canvas Bars", "Ifc4_SampleHouse.ifc",
     "Drag CAD toolbar handle across canvas: verify smooth dragging",
     "Verify tool mode buttons function in custom position"),
    ("C76", "Native Anti-Overlap Repulsion", "HudLayoutContext", "Draggable Canvas Bars", "Ifc2x3_SampleCastle.ifc",
     "Drag View Controls HUD directly onto Top Pill: verify overlap blocked",
     "Drag Bottom Dock onto Coordinate HUD: verify automatic edge repulsion"),
    ("C77", "Dimension Info Floating Card", "DimensionInfoHud", "3D Measurement", "Ifc2x3_Duplex_Architecture.ifc",
     "Place measurement in viewport: verify floating Dimension Info card mounts with distance and dx/dy/dz readouts",
     "Click Close (X) button on Dimension Info card: verify card unmounts while preserving dimension line"),
    ("C78", "Section Plane Offset Slider", "SpatialBottomDock", "BIM Tools & Sectioning", "Ifc4_SampleHouse.ifc",
     "Enable section plane: verify offset slider mounts with range [-20, 20]",
     "Drag slider to offset 5.0m: verify clipping plane shifts and scene cuts at +5m"),
    ("C79", "Camera Preset Dropdown Trigger", "SpatialBottomDock", "View Controls & Orientation", "Ifc2x3_SampleCastle.ifc",
     "Click camera icon trigger in dock: verify preset menu displays ISO, TOP, FRONT, SIDE",
     "Select FRONT from menu: verify camera re-orients and active preset updates"),
    ("C80", "Render Style Dropdown Trigger", "SpatialBottomDock", "Visibility & Styles", "Ifc2x3_Duplex_Architecture.ifc",
     "Click render style trigger in dock: verify styles menu displays PBR, Shaded, Wireframe, Discipline, Diff",
     "Select Wireframe from menu: verify render style switches and menu closes"),
    ("C81", "Coordinate HUD Selection Readout", "CoordinateHud", "Product Presence", "Ifc2x3_Duplex_Architecture.ifc",
     "Select element #128: verify signed coordinate readouts X/Y/Z render with + / - signs and millimeter precision",
     "Deselect element: verify coordinate box collapses to compact mesh counter"),
    ("C82", "Clash Filter Tabs", "ClashInspector", "Federation & Clashes", "Ifc2x3_Duplex_MEP.ifc",
     "Run clash check and switch to 'Hard' tab: verify only hard collisions listed",
     "Switch to 'Clearance' tab: verify clearance soft clashes filtered"),
    ("C83", "Timeline Range Scrubber Slider", "TimelineScrubber", "Session Audit & Playback", "Ifc4_Revit_STR.ifc",
     "Open timeline scrubber: verify slider min is 0 and max is timeline count - 1",
     "Drag slider to intermediate event: verify active event card updates"),
    ("C84", "Dimension HUD Copy Value Button", "DimensionInfoHud", "3D Measurement", "Ifc2x3_Duplex_Architecture.ifc",
     "Click copy button on active dimension HUD: verify formatted measurement string copied to clipboard",
     "Verify copy confirmation icon state toggles briefly"),
    ("C85", "Dimension HUD Delete Measurement Button", "DimensionInfoHud", "3D Measurement", "Ifc2x3_Duplex_Architecture.ifc",
     "Click trash/delete button on dimension HUD: verify measurement line and HUD deleted from scene",
     "Verify measurement count decrements in state"),
    ("C86", "Dimension HUD Close Card Button", "DimensionInfoHud", "3D Measurement", "Ifc2x3_Duplex_Architecture.ifc",
     "Click close button: verify HUD dismisses while measurement line remains in viewport",
     "Click measurement midpoint label in viewport: verify HUD re-opens"),
    ("C87", "Measure Active Banner Cancel Button", "ThreeViewport", "3D Measurement", "Ifc2x3_Duplex_Architecture.ifc",
     "Activate measure tool: verify top banner with instructions and Cancel button renders",
     "Click Cancel button in banner: verify measure mode exits cleanly and crosshair returns to default cursor"),
    ("C88", "Canvas Multi-Panel Resize Grippers", "ResizeHandle", "Viewport Ergonomics", "Ifc2x3_Duplex_Architecture.ifc",
     "Drag left tree drawer resize handle horizontally: verify drawer width adjusts smoothly",
     "Drag right property drawer resize handle: verify width expands/shrinks within clamped min/max"),
    ("C89", "Spatial Tree Filter Search Input", "SpatialTree", "Spatial Hierarchy", "Ifc2x3_Duplex_Architecture.ifc",
     "Open tree drawer and type 'Slab' in search input: verify tree filters nodes matching 'Slab'",
     "Clear search input: verify full hierarchy tree restores"),
    ("C90", "Spatial Tree Collapse/Expand Button", "SpatialTree", "Spatial Hierarchy", "Ifc2x3_Duplex_Architecture.ifc",
     "Click tree collapse button: verify tree drawer collapses to margin",
     "Click expand: verify drawer slides open with preserved tree node expansion"),
    ("C91", "Property Inspector Drawer Close Button", "PropertyInspector", "Property Inspection", "Ifc2x3_Duplex_Architecture.ifc",
     "Select element to open property drawer, click Close (X) button: verify property drawer closes cleanly",
     "Re-select element: verify property drawer mounts without errors"),
    ("C92", "Property Inspector Add Property Button", "PropertyInspector", "Property Inspection", "Ifc2x3_Duplex_Architecture.ifc",
     "Click '+ Add Property' button: verify new property entry field appears",
     "Cancel or blur property input: verify state remains stable"),
    ("C93", "Copilot Provider Settings Trigger", "CopilotSidebar", "AI BIM Copilot", "Ifc2x3_Duplex_Architecture.ifc",
     "Open Copilot drawer and click settings gear icon: verify Copilot Settings modal mounts",
     "Close settings modal: verify return to copilot conversation"),
    ("C94", "Copilot Gemini API Key Input", "CopilotSettingsModal", "AI BIM Copilot", "Ifc2x3_Duplex_Architecture.ifc",
     "In Copilot Settings modal, input Gemini API key and click Save: verify key stored in localStorage",
     "Re-open settings modal: verify key persists masked in password field"),
    ("C95", "Copilot Provider & Model Selectors", "CopilotSidebar", "AI BIM Copilot", "Ifc2x3_Duplex_Architecture.ifc",
     "Select provider 'gemini': verify model options update to Gemini models",
     "Select provider 'ollama': verify local model options populate"),
    ("C96", "Copilot Quick Action Chips", "CopilotSidebar", "AI BIM Copilot", "Ifc2x3_Duplex_Architecture.ifc",
     "Click 'Count elements by type' quick prompt chip: verify prompt auto-populates in input",
     "Click quick prompt with selected element: verify contextual prompt generated"),
    ("C97", "Copilot Chat Clear History Button", "CopilotSidebar", "AI BIM Copilot", "Ifc2x3_Duplex_Architecture.ifc",
     "With chat messages present, click trash icon: verify conversation history clears",
     "Verify welcoming empty state card renders"),
    ("C98", "CAD Parametric Settings Flyout", "CadToolbar", "Parametric CAD", "Ifc4_SampleHouse.ifc",
     "Click sliders/settings button on CAD toolbar: verify parametric settings card mounts",
     "Click sliders button again: verify settings card collapses"),
    ("C99", "CAD Wall Height & Thickness Inputs", "CadToolbar", "Parametric CAD", "Ifc4_SampleHouse.ifc",
     "Change wall height to 3.5m and thickness to 0.25m in settings card: verify parameters update",
     "Draw wall with modified parameters: verify synthesized wall matches custom dimensions"),
    ("C100", "Clash Inspector Close Button", "ClashInspector", "Federation & Clashes", "Ifc2x3_Duplex_MEP.ifc",
     "Open Clash Inspector HUD, click Close (X) button: verify HUD unmounts",
     "Verify clash wireframe bounding boxes remove from 3D viewport"),
    ("C101", "Clash Tolerance Radius Slider", "ClashInspector", "Federation & Clashes", "Ifc2x3_Duplex_MEP.ifc",
     "Change tolerance slider from 0.05m to 0.02m: verify value readout updates",
     "Click Run Clash Check: verify clash computation respects new tolerance parameter"),
    ("C102", "Clash Inspector Reposition Grip", "ClashInspector", "Draggable Canvas Bars", "Ifc2x3_Duplex_MEP.ifc",
     "Drag Clash Inspector grip by dx: 30, dy: 40: verify floating card repositions",
     "Verify collision list cards remain interactive in new location"),
    ("C103", "Federation Modal Close Button", "FederatedModelManager", "Federation & Clashes", "Ifc2x3_Duplex_MEP.ifc",
     "Open Federation Coordination modal, click Close (X) button: verify modal unmounts",
     "Open modal and click Done button in footer: verify modal dismisses"),
    ("C104", "Federated Submodel Visibility Eye Toggle", "FederatedModelManager", "Federation & Clashes", "Ifc2x3_Duplex_MEP.ifc",
     "Click eye toggle next to submodel: verify submodel meshes become hidden in viewport",
     "Click eye toggle again: verify submodel meshes reappear with discipline colors"),
    ("C105", "Federated Submodel Remove Button", "FederatedModelManager", "Federation & Clashes", "Ifc2x3_Duplex_MEP.ifc",
     "Click trash icon next to attached submodel: verify submodel detached and removed from layer list",
     "Verify model count indicator decrements"),
    ("C106", "BCF Manager Modal Close Button", "BcfManagerModal", "Collaboration & Issues", "Ifc2x3_Duplex_MEP.ifc",
     "Open BCF Manager modal, click Close (X) button: verify modal unmounts",
     "Verify canvas viewport retains focus"),
    ("C107", "BCF Issue Topic Card Selection", "BcfManagerModal", "Collaboration & Issues", "Ifc2x3_Duplex_MEP.ifc",
     "Click topic card in BCF list: verify topic selected and associated elements highlight",
     "Click viewpoint camera button on topic: verify 3D camera animates to saved topic perspective"),
    ("C108", "Timeline Scrubber Close Button", "TimelineScrubber", "Session Audit & Playback", "Ifc4_Revit_STR.ifc",
     "Open Timeline Scrubber HUD, click Close (X) button: verify scrubber unmounts",
     "Verify selection state persists upon closing"),
    ("C109", "Timeline Active Event Preview Card", "TimelineScrubber", "Session Audit & Playback", "Ifc4_Revit_STR.ifc",
     "Scrub to transform event: verify event card displays user name, action type, timestamp, and element ID",
     "Click event card or step to it: verify associated element selected in 3D scene"),
    ("C110", "New Project Modal Tabs & Name Input", "NewProjectModal", "Project Lifecycle", "Building-Architecture.ifc",
     "Open New Project modal, switch between 'Blank Project' and 'Sample Models' tabs: verify tab switching",
     "In Blank Project tab, type project name and select schema: verify submit button becomes enabled"),
    ("C111", "Upload Modal Dropzone & Dismiss Button", "UploadModal", "Project Lifecycle", "Building-Architecture.ifc",
     "Open Upload modal: verify dropzone displays file drag instructions and supported schemas",
     "Click Close (X) button: verify modal cleanly dismisses without upload"),
    ("C112", "Collaborative Soft-Lock Notification & Dismiss", "App", "Real-Time Collaboration", "Building-Architecture.ifc",
     "Trigger soft-lock warning for element #105 held by another collaborator: verify floating amber alert renders",
     "Click dismiss (X) button on soft-lock alert: verify banner closes cleanly")
]

def main():
    existing_lines = []
    if TEST_CASES_FILE.exists():
        with open(TEST_CASES_FILE, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    data = json.loads(line)
                    # Keep only TC-001 through TC-097
                    if data["id"].startswith("TC-") and int(data["id"][3:]) <= 97:
                        existing_lines.append(data)
                except Exception:
                    pass

    print(f"Loaded {len(existing_lines)} baseline test cases (TC-001 to TC-097).")

    # Add TC-098 and TC-099
    tc_098 = {
        "id": "TC-098",
        "category": "Draggable Canvas Bars",
        "tier": "key",
        "name": "Draggable Canvas Bars & Floating HUD Grips",
        "description": "Verify all floating canvas bars (Top Pill, View Controls, Bottom Dock, Coordinate HUD, CAD Toolbar, Timeline Scrubber, Clash Inspector) have interactive drag handles and move smoothly",
        "preconditions": ["UI loaded at http://localhost:5173", "Canvas HUDs mounted"],
        "steps": [
            "Inspect Top Pill for data-drag-handle",
            "Dispatch drag on Top Pill handle by 40px, 30px",
            "Verify Top Pill updates fixed coordinates",
            "Inspect View Controls HUD for drag handle and drag by -50px, 40px",
            "Verify View Controls updates fixed position"
        ],
        "expected": "Canvas bars reposition fluidly via mouse dragging with active cursor indicators",
        "platforms": ["http://localhost:5173"],
        "model": "Building-Architecture.ifc"
    }

    tc_099 = {
        "id": "TC-099",
        "category": "Draggable Canvas Bars",
        "tier": "key",
        "name": "Native Anti-Overlap Collision Repulsion & Boundary Clamping",
        "description": "Verify floating HUDs detect AABB collisions and automatically separate with 12px clearance, never occluding each other or escaping viewport boundaries",
        "preconditions": ["UI loaded at http://localhost:5173", "HudLayoutProvider active"],
        "steps": [
            "Drag View Controls HUD into candidate coordinates colliding with Spatial Top Pill",
            "Verify resolveOverlap computes minimum displacement and pushes View Controls outside Top Pill bounding box with 12px clearance",
            "Drag bar towards screen border beyond window limits",
            "Verify coordinates clamp to viewport boundaries [8, max-8]"
        ],
        "expected": "HUDs block visual overlaps natively and stay fully contained within viewport boundaries",
        "platforms": ["http://localhost:5173"],
        "model": "Ifc2x3_SampleCastle.ifc"
    }

    all_cases = existing_lines + [tc_098, tc_099]

    # Generate Scenario A and Scenario B for each of the 76 UI controls
    for code, control_name, component, category, model, scen_a, scen_b in UI_CONTROLS:
        # Scenario A
        tc_a = {
            "id": f"TC-{code}-A",
            "category": category,
            "tier": "key" if code in ["C01", "C02", "C18", "C19", "C20", "C26", "C27", "C32", "C33", "C34", "C35", "C37", "C41", "C42", "C72", "C73", "C74", "C76"] else "full",
            "name": f"[{code}] {control_name} — Scenario A",
            "description": f"Live test Scenario A for {control_name} ({component}): {scen_a}",
            "preconditions": [f"Model {model} loaded in viewport", f"Control {control_name} mounted"],
            "steps": [
                f"Verify control {control_name} is rendered in {component}",
                f"Execute primary action: {scen_a}",
                "Evaluate functional state and DOM/WebGL response"
            ],
            "expected": f"Scenario A succeeds: {scen_a}",
            "platforms": ["http://localhost:5173"],
            "model": model,
            "control_id": code,
            "control_name": control_name,
            "scenario": "A"
        }

        # Scenario B
        tc_b = {
            "id": f"TC-{code}-B",
            "category": category,
            "tier": "key" if code in ["C01", "C02", "C18", "C19", "C20", "C26", "C27", "C32", "C33", "C34", "C35", "C37", "C41", "C42", "C72", "C73", "C74", "C76"] else "full",
            "name": f"[{code}] {control_name} — Scenario B",
            "description": f"Live test Scenario B for {control_name} ({component}): {scen_b}",
            "preconditions": [f"Model {model} loaded in viewport", f"Control {control_name} mounted"],
            "steps": [
                f"Verify control {control_name} is rendered in {component}",
                f"Execute edge / alternate action: {scen_b}",
                "Evaluate functional state and DOM/WebGL response"
            ],
            "expected": f"Scenario B succeeds: {scen_b}",
            "platforms": ["http://localhost:5173"],
            "model": model,
            "control_id": code,
            "control_name": control_name,
            "scenario": "B"
        }

        all_cases.extend([tc_a, tc_b])

    print(f"Total compiled test suite: {len(all_cases)} test cases.")

    with open(TEST_CASES_FILE, "w", encoding="utf-8") as f:
        for c in all_cases:
            f.write(json.dumps(c, ensure_ascii=False) + "\n")

    print(f"Wrote {len(all_cases)} test cases to {TEST_CASES_FILE.name}.")

if __name__ == "__main__":
    main()
